### ISSUE TITLE
value of "water remain" for zhimi.humidifier.ca1

### ISSUE THREAD

**Issue by co-Palko** [smarthomefans/ioBroker.miio#12]
in MiHome  app, value is 0-100%, in ioBroker.miio value is 0-120.
These theme up in other driver [https://github.com/aholstenson/miio/issues/131#issuecomment-376881949](url)

**Comment by SchumyHao** [comment]
Thank you. I'll check this ASAP

**Comment by SchumyHao** [comment]
Issue may fix in this commit df2894df239751d3ed361fcdd915b492ab605c8d
And will publish with 0.0.12
