### ISSUE TITLE
chuangmi.plug.m1 support

### ISSUE THREAD

**Issue by VLGorskij** [smarthomefans/ioBroker.miio#13]
Good afternoon, SchumyHao!
I tested the adapter 0.0.7 (2019-05-17) with the device chuangmi.plug.m1 on Raspberry PI3. Everything works perfectly!
Thanks for your adapter!

**Comment by VLGorskij** [comment]
Updated the adapter version to 0.0.9 and was upset. Can you fix that?


![miio](https://user-images.githubusercontent.com/45288874/60258799-8ac77580-98de-11e9-82f1-ff1f32ae410a.png)

**Comment by VLGorskij** [comment]
Reinstalled version 0.0.7 - everything works again!
![miio1](https://user-images.githubusercontent.com/45288874/60260212-b13ae000-98e1-11e9-8a2d-aa63833de8f0.png)

![miio2](https://user-images.githubusercontent.com/45288874/60260234-b9931b00-98e1-11e9-9884-51cbfb03c80c.png)

**Comment by SchumyHao** [comment]
OK Thank you for your response.
I'll fix it tonight

**Comment by SchumyHao** [comment]
Issue will fixed in #14

**Comment by VLGorskij** [comment]
Good day! Installed version 0.0.10, alas, the miracle did not happen ...


![1miio](https://user-images.githubusercontent.com/45288874/60567178-d318e480-9d71-11e9-8513-58de2c43e7eb.png)


![2 miio](https://user-images.githubusercontent.com/45288874/60567189-db711f80-9d71-11e9-8163-d25c052d1cc6.png)


I'll be back at 0.0.7

**Comment by SchumyHao** [comment]
Another issue :( 
But I'll fix it

**Comment by SchumyHao** [comment]
Update version 0.0.11.
Remove one unused function, which required a module that not installed.
This maybe can fix this issue.

I tested on chuangmi.plug.v3, it works.

If it still can not work, may you removed the channel and all state of this device?

**Comment by VLGorskij** [comment]
Good evening! I am very pleased with your quick reaction to the problem, but unfortunately I can’t fulfill your recommendations so far as there is no version 0.0.11 on GitHub. As soon as it is available, I will test it and let you know the result.03.07.2019, 19:49, "SchumyHao" <notifications@github.com>:Update version 0.0.11.
Remove one unused function, which required a module that not installed.
This maybe can fix this issue.
I tested on chuangmi.plug.v3, it works.
If it still can not work, may you removed the channel and all state of this device?

**Comment by VLGorskij** [comment]
Good morning! SchumyHao, I tested version 0.0.11 with a chuangmi.plug.m1 socket.
All perfectly!!!

![3 miio](https://user-images.githubusercontent.com/45288874/60698980-9af0dd80-9efa-11e9-93a7-676bbb715571.png)

Thank you so much!

**Comment by SchumyHao** [comment]
Glad to hear that~
