### ISSUE TITLE
It seems this adapter can not exit totally

### ISSUE THREAD

**Issue by SchumyHao** [smarthomefans/ioBroker.miio#15]
In some situation, this adapter can not exit totally, and this adapter can not run again.

log shows:

instance system.adapter.miio.0 terminated with code 7 (Adapter already running)
--

**Comment by enemy2003** [comment]
I got this, when there is a process running on my server that acts like a zombie. After reinstallation or something like that. Stop the adapter, check if there is still a io.miio.0 process and kill it, then start the adapter again. This works for me. Got the same for other adapters too, so maybe not an adapter bug?

**Comment by SchumyHao** [comment]
kill process also works for me, but i think this is not best solution:flushed:

**Comment by SchumyHao** [comment]
js-controller 2.0 will handle this issue
