### ISSUE TITLE
SMART FAN TOKEN

### ISSUE THREAD

**Issue by hyperbit00** [smarthomefans/ioBroker.miio#18]
I Add the FAN with the IP Address (nothing else)

Log says ERROR

miio.0 | 2019-08-28 18:03:30.688 | warn | XXXXXXXXXXX can not be connected.Error: Could not connect to device, token might be wrong
-- | -- | -- | --
miio.0 | 2019-08-28 18:03:15.007 | info | Start auto discover

**Comment by hyperbit00** [comment]
SOLVED: 

https://www.home-assistant.io/components/vacuum.xiaomi_miio/#retrieving-the-access-token

**Comment by SchumyHao** [comment]
Close this as you can retrieving token by your self
