### ISSUE TITLE
Smart Fan only Read, no set

### ISSUE THREAD

**Issue by hyperbit00** [smarthomefans/ioBroker.miio#19]
It's only possible to read Values, but not set!
Is it a Bug?

Want to Set Power and Speed, but did not work.

**Comment by olli0815** [comment]
I would like to ask exactly the same question ;-).
Fan is recognized, values can be changed within the object, but the fan doesn't react on changes 

EDIT: I checked other divices, at least here I can't control any divice as for instance philips.light.bulb can not be switched on / off

**Comment by SchumyHao** [comment]
thank you for your reply. this issue happened all the time? or it happen after adapter updated?

**Comment by hyperbit00** [comment]
Happens all the time, with this adapter and the smart Fan.

All Others Adapters working like a Charm.

It seems to be a IObroker.miio Problem.

**Comment by olli0815** [comment]
In other words: at least here I wasn't able to  control the devices at all. I can change the values  in IOB without any effect to any of the devices. So is it definitely not a device specific issue.

Hope that helps 
Oliver

**Comment by p0rys** [comment]
Can confirm this error. After adding my "zhimi.fan.za4" and "zhimi.airpurifier.mc1" it can read the status just fine, but i cant set a value from IoBroker.

If you need any logs or something please let me know!

**Comment by SchumyHao** [comment]
I can reproduce this issue too.
But I need more time to fix it.
Because I don't have seperate time for this days.

**Comment by olli0815** [comment]
cool thanks. if you need support (testing) let me know ;-)

**Comment by SchumyHao** [comment]
I think this may fix this issue https://github.com/smarthomefans/ioBroker.miio/commit/b97417c544a10ef6bd65928579d555f27c6d19a9
And I bump version to 0.0.12 to fix this issue

**Comment by olli0815** [comment]
sorry at least here the issue is not fixt

**Comment by p0rys** [comment]
For me, deleting all objects and update the adapter via github fixed the control issue! Thank you very much @SchumyHao! 

Another question: Is it possible to get the chargeState / percentage for zhimi.fan.za4? It was available before but not filled with any data... Not sure if the device supports these states.

**Comment by olli0815** [comment]
okay,okay it is fixed.
I deleted the fan - entered the token again, restarted the adapter and  I am able to control it !
Thanks, again and apologize for the wrong error message
