### ISSUE TITLE
support request: zhimi.fan.za4

### ISSUE THREAD

**Issue by enemy2003** [smarthomefans/ioBroker.miio#20]
Would like to add my Smartmi Fan S2 (zhimi.fan.za4). Got the correct token with the tutorial.

In the log I got: zhimi.fan.za4 is not supported for now.

If I can help to support it, let me know.

// I did a fork and added a configuration for the za4 in the same way as the v3 and that works fine for most of the functionality :)

**Comment by p0rys** [comment]
Can you control the fan after adding the configuration? I tried my "zhimi.fan.za4" yesterday and i could add it and read values but not set anything. See #19

**Comment by enemy2003** [comment]
Yes it works to control it

**Comment by p0rys** [comment]
Did you do anything special on your local installation (updated external packages etc)? I tried your fork on my device and i still can't control it. Just reading some of the states (e.g. motorSpeed and power but e.g. temperature is always null) ...

**Comment by SchumyHao** [comment]
I do nothing, and I find the devices in my home can not controlled too.
I'll fix this issue in two or three days.

**Comment by SchumyHao** [comment]
Hi @p0rys 

I think you can try to remove old objects if you used previous version of this adapter
![image](https://user-images.githubusercontent.com/4982108/64869942-f5ce5000-d674-11e9-8949-f760d17e17c4.png)

Because I remember that I add `device` object.
If you can not control after you deleted all object, just let me know

**Comment by SchumyHao** [comment]
Hi @p0rys 
Please update to 0.0.12.
This version of adapter will update outdate objects to new ones
