### ISSUE TITLE
can`t delete device from list

### ISSUE THREAD

**Issue by co-Palko** [smarthomefans/ioBroker.miio#9]
Can`t delete device zhimi.humidifier.ca1 from list. 
After delete and save, it reappears in the list. 
Restart of driver not helping. 
Deleting objects in miio driver not helping;

**Comment by SchumyHao** [comment]
Thank you for your reply. I'll check this issue later

**Comment by SchumyHao** [comment]
Hi @co-Palko 
I think you can disable auto discover first. Then delete device.
![image](https://user-images.githubusercontent.com/4982108/60154223-33ab9d00-9819-11e9-98f5-a2c7b6010865.png)

**Comment by co-Palko** [comment]
Hi! Nop. not working.
Disable auto discover, then save. Delete item, then "save and exit". 
When I come back, my device is here...

PS I have only one device.

**Comment by SchumyHao** [comment]
Thank you @co-Palko 
Issue fixed with this patch 8868ebccb7495aeb5135e98aa3258456f1fe985a
